"""initial_schema

Revision ID: a58901b72a94
Revises: 
Create Date: 2026-06-26 18:36:30.614543

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a58901b72a94'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=False),
    sa.Column('claim_code', sa.String(length=20), nullable=False),
    sa.Column('provider_npi', sa.String(length=20), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billed_currency', sa.String(length=3), nullable=False),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_currency', sa.String(length=3), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_claim_code'), 'invoices', ['claim_code'], unique=False)
    op.create_index(op.f('ix_invoices_member_id'), 'invoices', ['member_id'], unique=False)
    op.create_table('anomaly_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_results_invoice_id'), 'anomaly_results', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_results_invoice_id'), table_name='anomaly_results')
    op.drop_table('anomaly_results')
    op.drop_index(op.f('ix_invoices_member_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_claim_code'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
